[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[etherscan]
  optimism-sepolia = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  base-sepolia = { key = "${API_KEY_BASESCAN}" }

[rpc_endpoints]
  optimism-sepolia = "https://opt-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
